### ISSUE TITLE
Suggestion: switch to Discord Timeouts

### ISSUE THREAD

**Issue by net-tech** [Benricheson101/anti-phishing-bot#17]
Switch mute action to the new Discord Timeouts feature

**Comment by User9684** [comment]
There's currently no way for a permanent timeout, so I don't think this will happen any time soon

**Comment by Benricheson101** [comment]
This is actually something I've been meaning to do for the last few weeks. Hope to get it done within the next week or so!

**Comment by net-tech** [comment]
@Benricheson101 Hey there, any updates?
